use_frameworks!

target 'XZMessageView_Example' do
  pod 'XZMessageView', :path => '../'

  target 'XZMessageView_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
  pod 'FBSnapshotTestCase'
  end
end
